server:
  port: 8000
spring:
  config:
    import: application-secret.yml  # 시크릿 키 숨기기
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/goodplace/user-management/**
          filters:
            - RewritePath=/goodplace/user-management/(?<segment>.*), /${segment}

        - id: blog-service
          uri: http://localhost:8081  # Blog Service 직접 연결
          predicates:
            - Path=/goodplace/blog-service/**
          filters:
            - RewritePath=/goodplace/blog-service/(?<segment>.*), /${segment}