server:
  port: 8000
spring:
  config:
    import: application-secret.yml  # 시크릿 키 숨기기
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/user-management/**
          filters:

            - RewritePath=/api/user-management/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

